import { initRouter } from '@cqdcg/admin/router/index';
import { staticRoutes, notFoundAndNoPower, dynamicRoutes, baseRoutes } from '/@/router/route';
// const layouModules: any = import.meta.glob('../layout/routerView/*.{vue,tsx}');
const viewsModules: any = import.meta.glob('../views/**/*.{vue,tsx}');
let router = initRouter({
	dynamicRoutes,
	staticRoutes,
	baseRoutes,
	notFoundAndNoPower,
	dynamicViewsModules: {
		...viewsModules,
		'@cqdcg/home': () => import('@cqdcg/admin/views/admin/system/user/index'),
		'@cqdcg/menu': () => import('@cqdcg/admin/views/admin/system/menu/index'),
		'@cqdcg/permission': () => import('@cqdcg/admin/views/admin/system/permission/index'),
		'@cqdcg/role': () => import('@cqdcg/admin/views/admin/system/role/index'),
		'@cqdcg/dept': () => import('@cqdcg/admin/views/admin/system/dept/index'),
		'@cqdcg/post': () => import('@cqdcg/admin/views/admin/system/post/index'),
		'@cqdcg/tenant': () => import('@cqdcg/admin/views/admin/system/tenant/index'),
		'@cqdcg/audit': () => import('@cqdcg/admin/views/admin/audit/index'),
		'@cqdcg/log': () => import('@cqdcg/admin/views/admin/log/index'),
		'@cqdcg/dict': () => import('@cqdcg/admin/views/admin/dict/index'),
		'@cqdcg/file': () => import('@cqdcg/admin/views/admin/file/index'),
		'@cqdcg/param': () => import('@cqdcg/admin/views/admin/param/index'),
		'@cqdcg/i18n': () => import('@cqdcg/admin/views/admin/i18n/index'),
		'@cqdcg/client': () => import('@cqdcg/admin/views/admin/client/index'),
		'@cqdcg/social': () => import('@cqdcg/admin/views/admin/social/index'),
		'@cqdcg/token': () => import('@cqdcg/admin/views/admin/token/index'),
		'@cqdcg/sysArea': () => import('@cqdcg/admin/views/admin/sysArea/index'),
		'@cqdcg/tools/data': () => import('@cqdcg/admin/views/tools/data/cache'),
		'@cqdcg/tools/route': () => import('@cqdcg/admin/views/tools/route/index'),
		'@cqdcg/tools/job-manage': () => import('@cqdcg/admin/views/tools/job-manage/index'),
		'@cqdcg/tools/message': () => import('@cqdcg/admin/views/tools/message/index'),
		'@cqdcg/flow/task/pending': () => import('@cqdcg/admin/views/flow/task/pending'),
		'@cqdcg/flow/task/examine': () => import('@cqdcg/admin/views/flow/task/examine'),
		'@cqdcg/flow/task/started': () => import('@cqdcg/admin/views/flow/task/started'),
		'@cqdcg/flow/task/cc': () => import('@cqdcg/admin/views/flow/task/cc'),
		'@cqdcg/flow/task/completed': () => import('@cqdcg/admin/views/flow/task/completed'),
		'@cqdcg/flow/list/index': () => import('@cqdcg/admin/views/flow/list/index'),
		'@cqdcg/flow/create/all': () => import('@cqdcg/admin/views/flow/create/all'),
		'@cqdcg/flow/group/index': () => import('@cqdcg/admin/views/flow/group/index'),
		'@cqdcg/flow/packet/index': () => import('@cqdcg/admin/views/flow/packet/index'),
		'@cqdcg/gen/datasource/index': () => import('@cqdcg/admin/views/gen/datasource/index'),
		'@cqdcg/gen/create-table/index': () => import('@cqdcg/admin/views/gen/create-table/index'),
		'@cqdcg/gen/table/index': () => import('@cqdcg/admin/views/gen/table/index'),
		'@cqdcg/gen/design/index': () => import('@cqdcg/admin/views/gen/design/index'),
		'@cqdcg/gen/field-type/index': () => import('@cqdcg/admin/views/gen/field-type/index'),
		'@cqdcg/gen/template/index': () => import('@cqdcg/admin/views/gen/template/index'),
		'@cqdcg/gen/group/index': () => import('@cqdcg/admin/views/gen/group/index'),
	},
});
export default router;
