version: '3'
services:
  projectmgt-ui:
    build:
      context: .
    restart: always
    container_name: projectmgt-ui
    image: projectmgt-ui
    networks:
      - spring_cloud_default
    external_links:
      - projectmgt-gateway
    ports:
      - 80:80

# 加入到后端网络， 默认为 projectmgt_default  | docker network ls   查看
networks:
  spring_cloud_default:
    external: true
